### ISSUE TITLE
Invalid response from the bKash Server.

### ISSUE THREAD

**Issue by viphostbd** [NawabHost/bkash-tokenized-checkout-for-whmcs#1]
Dear Sir,
I am setup your module but when i used live credential then Feedback me a massage of Invalid response from the bKash Server. How to solutions its ?

**Comment by AminulBD** [comment]
Please see this: https://github.com/NawabHost/bkash-checkout-for-whmcs/issues/11#issuecomment-1132766567

**Comment by zehadulislam** [comment]
I see everything fine in my module setting but your module isn't working properly. its showing error

**Comment by zehadulislam** [comment]
I see everything fine in my module setting but your module isn't working properly. its showing error. 
![image](https://github.com/NawabHost/bkash-tokenized-checkout-for-whmcs/assets/36853107/74d77c4e-97bd-4db2-989e-fe1000b11a97)

**Comment by AminulBD** [comment]
@zehadulislam The System URL and Domain should be same in the general settings.

**Comment by zehadulislam** [comment]
All setup are okay. but showing error.
