### ISSUE TITLE
json response

### ISSUE THREAD

**Issue by sykot** [NawabHost/bkash-tokenized-checkout-for-whmcs#3]
Hello,
Can you please share how to get "Create Payment Sandbox Test" & "Execute Payment Sandbox Test" json response?
Thanks

![Screenshot 2024-05-21 at 9 06 38 PM](https://github.com/NawabHost/bkash-tokenized-checkout-for-whmcs/assets/190126/bfa9f4a8-1f2f-4100-b883-d1f60a4ec7c6)

**Comment by AminulBD** [comment]
Hi,

This extension doesn't provide any json for data fill-up this. You have to do it manually via their API platform or something else by yourself.

Thanks.

> FYI: If you purchased Pro version of this extension, then we can generate your requested responses for you.
